_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 2f3d4cfc-9bf6-4b27-97ef-50a6ed8779ea
name: ShopKart
mail: tirupati.singh@innoraft.com
slogan: ''
page:
  403: /node/87
  404: /node/88
  front: /node/86
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
